dist: trusty
language: php

sudo: false

php:
  - 5.3
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - env: SYMFONY_VERSION=^2
    - env: SYMFONY_VERSION=^3
    - env: SYMFONY_VERSION=^4
    - env: SYMFONY_VERSION=^5
#    - php: 5.3
#      env: SYMFONY_VERSION=^2
#    - php: 5.5
#      env: SYMFONY_VERSION=^3
#    - php: 7.1
#      env: SYMFONY_VERSION=^2
#    - php: 7.1
#      env: SYMFONY_VERSION=^3
#    - php: 7.2
#      env: SYMFONY_VERSION=^4
#    - php: 7.2
#      env: SYMFONY_VERSION=^5
#    - php: 7.3
#      env: SYMFONY_VERSION=^4
#    - php: 7.3
#      env: SYMFONY_VERSION=^5
#    - php: 7.4
#      env: SYMFONY_VERSION=^4
#    - php: 7.4
#      env: SYMFONY_VERSION=^5

before_install:
  - composer self-update

install:
  - composer require symfony/yaml:${SYMFONY_VERSION}

scripts: ./vendor/bin/phpunit tests/
